### ISSUE TITLE
Stream writing

### ISSUE THREAD

**Issue by jose-sherpa** [kputnam/stupidedi#264]
We have a use case where we will be building large edi files. Currently it seems like the entire tree is stored in memory which is not ideal. Is it possible to write each line as it is generated and then discard?

**Comment by kputnam** [comment]
You are correct, the entire transaction set is stored in memory. There is not a way to work around this -- however you could mitigate it by not creating multiple transaction sets (ST/SE) functional groups (GS/GE) within one interchange (ISA/ISE). You can emit the entire document once you generate the ISE segment, then discard the parser to free memory before creating a new ISA/GS/ST envelope.

**Comment by kputnam** [comment]
Memory consumption in this library is particularly bad for large files. It's due to copying single characters and substrings -- all of it comes from the same input string, it's just chopped up into many different objects. There's an PR open where I made some big improvements. I wish I had merged it while I had momentum.

Instead I went for even better optimizations by implementing some parts in C. That work is still viable but I just don't have the momentum right now to merge it.
