### ISSUE TITLE
Adding the additional accepted values for a segement

### ISSUE THREAD

**Issue by saikiran0208** [kputnam/stupidedi#268]
how can i add more accepted values for a segment lets say REF, are there any built-in methods or any ways to do it

**Comment by kputnam** [comment]
Hi, it depends on the circumstances. I assume you are talking about changing this for a particular `TransactionSetDef` -- either a transaction set standard or an implementation. The difference between the two is a bit of X12 trivia, but implementations are basically a "narrowed down" standard. The standard defines some grammar that is either required or optional, and the implementation can skip optional things but it must keep required things.

So if you want to change an transaction set implementation, you would make a copy of the definition in a new file. Then you'd edit a line like [this one](https://github.com/kputnam/stupidedi/blob/9e1b9896b371078d439e72505165082b898cd00a/lib/stupidedi/transaction_sets/005010/implementations/X212-HR276.rb#L44). In that example I'm changing an `NM1` segment defined [here](https://github.com/kputnam/stupidedi/blob/9e1b9896b371078d439e72505165082b898cd00a/lib/stupidedi/versions/005010/segment_defs/NM1.rb) and in particular, the element within the segment I'm changing is the 8th one, which is this [`E66`](https://github.com/kputnam/stupidedi/blob/9e1b9896b371078d439e72505165082b898cd00a/lib/stupidedi/versions/005010/segment_defs/NM1.rb#L19C16-L19C16) element. That element is defined [here](https://github.com/kputnam/stupidedi/blob/9e1b9896b371078d439e72505165082b898cd00a/lib/stupidedi/versions/005010/element_defs.rb#L17-L57), where you can see the full list of allowed values.

If you want to allow a value that's within that full set, you're fine and just need to add it in your transaction set definition. But you cannot specify values that aren't in the definition for the element, because that would violate X12 standards. One of the main design goals of this library is to prevent the creation of invalid documents that would be rejected by a trading partner -- with medical billing, this could result in negative financial consequences for a physician's office.

But when I developed the library, I only had a limited set of documentation on X12, namely the 5010 HIPAA transaction set definitions. That means there are things which may be valid with respect to X12 standards that aren't included in the definitions in the library. You can submit a PR to add them if you can provide reasonable evidence that the standard permits it -- this means something besides a single trading partner, but something like a clearing house or a validation service, or even X12 documentation. I'm happy to accept PRs like this.

If you can't provide this evidence, I recommend skipping the PR and forking a copy of the library for your own use. You might be able to edit the list at runtime, which means you don't need to fork, but it is a crude approach. Maybe a feature like the ability to edit schemas at runtime would come in handy, but it's mostly against the design goals so I'm not likely to build it.

Because this particular change might require editing an ElementDef, it potentially affects every other grammar shipped with the library within the same X12 version. Other changes to grammars are not as invasive, so if you want to add a missing segment to a transaction set, or remove one, etc, this can be done by simply copying the transaction set definition, moving it some place in your application, making your edits, and then wiring it in with a `Config` constructor method like [this one](https://github.com/kputnam/stupidedi/blob/9e1b9896b371078d439e72505165082b898cd00a/lib/stupidedi/config.rb#L94-L103).
