### ISSUE TITLE
stupidedi does not add end segments

### ISSUE THREAD

**Issue by andrewthad** [kputnam/stupidedi#53]
In the example for generating an EDI file on README.md, the declarations of the end segments are omitted. I assumed that this was because stupidedi would generate them for me. However, when I copy that example into a ruby script and then change the definition of `config` to the following:

```
config = Stupidedi::Config.default
config.interchange.register("00501") {Stupidedi::Versions::Interchanges::FiveOhOne::InterchangeDef}
config.functional_group.register("005010") {Stupidedi::Versions::FunctionalGroups::FiftyTen::FunctionalGroupDef}
config.transaction_set.register("005010X222", "HC", "837") {Stupidedi::Guides::FiftyTen::X222::HC837P }
b = Stupidedi::Builder::BuilderDsl.build(config)
```

I have to change this definition or else it doesn't work at all. Anyway, when I do this, the output I get is missing the SE, GE, and IEA segments.

**Comment by gisborne** [comment]
I'm a little confused. This:

`      m = builder.machine
      builder.SE(2 + m.distance(m.parent), "0001")
`
appears to be what should generate a correct SE, but I get "NoMethodError: undefined method `zipper'"

**Comment by kputnam** [comment]
It looks like the problem is `m.parent` is not a `StateMachine` (where has `zipper` defined). Looking at the documentation, the return type of `m.parent` is `Either<StateMachine>`; this is because an empty tree has no parent, so the result is wrapped.

You can read about how to use `Either` values here (really, we should make a separate document just about `Either`):
* <https://github.com/kputnam/stupidedi/blob/master/doc/Navigating.md#chaining-method-calls>
* <https://github.com/kputnam/stupidedi/blob/master/doc/Navigating.md#current-segment>

Something like this should be close to what you want:
```ruby
m = builder.machine
m.parent.tap do |p|
  builder.SE(2 + m.distance(p), "0001")
end
```

**Comment by kputnam** [comment]
Also, if you look at the example @andrewthad pasted, you can use `m.parent.fetch` which will return the `StateMachine` if `m.parent` was a success or return `nil` on failure.
