### ISSUE TITLE
Generator example returns parse error

### ISSUE THREAD

**Issue by dajwilli** [kputnam/stupidedi#69]
I am looking to use this gem to generate 837 professional claim file. ButI can't get the example provided for generating claims to work. The following error is return when trying to generate the ST data segment:

Stupidedi::Exceptions::ParseError: unknown transaction set "HC" "837" "005010X222"

Do I have to set some config settings for the transaction header?

**Comment by kputnam** [comment]
Thanks for reporting this. Was the example you followed [this one](https://github.com/kputnam/stupidedi#generating-writing) from the README?

The line near the top should read `config = Stupidedi::Config.hipaa`. Since writing the README, the HIPAA grammars (including 837) were removed from `default` constructor and put into the `hipaa` constructor.
