### ISSUE TITLE
834 fails on parsing

### ISSUE THREAD

**Issue by michaelachrisco** [kputnam/stupidedi#71]
https://github.com/kputnam/stupidedi/blob/master/spec/fixtures/X220-BE834/3-good.txt
Fails on parsing 834 data:
```
TransmissionVal(
  InterchangeVal[00501](
    SegmentVal[ISA: Interchange Control Header](
      ID.value[  I01: Authorization Information Qualifier](00: No Authorization Information Present (No Meaningful Information in I02)),
      AN.value[  I02: Authorization Information](..........),
      ID.value[  I03: Security Information Qualifier](01: Password),
      AN.value[  I04: Security Information](SECRET....),
      ID.value[  I05: Interchange ID Qualifier](ZZ: Mutually Defined),
      AN.value[  I06: Interchange Sender ID](SUBMITTERS.ID..),
      ID.value[  I05: Interchange ID Qualifier](ZZ: Mutually Defined),
      AN.value[  I07: Interchange Receiver ID](RECEIVERS.ID...),
      DT.value[  I08: Interchange Date](XX03-01-01),
      TM.value[  I09: Interchange Time](12:53:ss),
      SeparatorElementVal.value[I65](^),
      ID.value[  I11: Interchange Control Version Number](00501: Standards Approved for Publication by ASC X12 Procedures Review Board through October 2003),
      Nn.value[  I12: Interchange Control Number](905),
      ID.value[  I13: Acknowledgment Requested](1: Interchange Acknowledgment Requested (TA1)),
      ID.value[  I14: Interchange Usage Indicator](T: Test Data),
      SeparatorElementVal.value[I15](:)), 
    FunctionalGroupVal[005010](
      SegmentVal[GS: Functional Group Header](
        ID.value[ E479: Functional Identifier Code](BE: Benefit Enrollment and Maintenance),
        AN.value[ E142: Application's Sender Code](SENDER CODE),
        AN.value[ E124: Application Receiver's Code](RECEIVER CODE),
        DT.value[ E373: Date](1999-12-31),
        TM.value[ E337: Time](08:02:ss),
        Nn.value[  E28: Group Control Number](1),
        ID.value[ E455: Responsible Agency Code](X: Accredited Standards Committee X12),
        AN.value[ E480: Version / Release / Identifier Code](005010X220)), 
      InvalidEnvelopeVal(
        unknown transaction set "BE" "834" "005010X220",
        InvalidSegmentVal[ST],
        InvalidSegmentVal[BGN],
        InvalidSegmentVal[N1],
        InvalidSegmentVal[N1],
        InvalidSegmentVal[INS],
        InvalidSegmentVal[REF],
        InvalidSegmentVal[REF],
        InvalidSegmentVal[DTP],
        InvalidSegmentVal[NM1],
        InvalidSegmentVal[PER],
        InvalidSegmentVal[N3],
        InvalidSegmentVal[N4],
        InvalidSegmentVal[DMG],
        InvalidSegmentVal[HD],
        InvalidSegmentVal[DTP],
        InvalidSegmentVal[LX],
        InvalidSegmentVal[NM1],
        InvalidSegmentVal[SE]), 
      SegmentVal[GE: Functional Group Trailer](
        Nn.value[  E97: Number of Transaction Sets Included](1),
        Nn.value[  E28: Group Control Number](1))), 
    SegmentVal[IEA: Interchange Control Trailer](
      Nn.value[  I16: Number of Included Functional Groups](1),
      Nn.value[  I12: Interchange Control Number](905))))
22 segments
0.139 seconds
```

Looks as if it does not like the transaction set BE. Ive also run this over some "valid" 834 files in my company with the same result, getting stuck in set BE. 

Any ideas?

**Comment by kputnam** [comment]
Hi Michael, that error message means the `config` doesn't have a mapping from "BE" "834" "005010X220" to a grammar (either a `Guide` or a `TransactionSetDef`). While I included those example files, I didn't have documentation about the grammar, so I wasn't able to implement that.

If you have some documentation, you can implement your own grammar; it's usually straightforward if a bit tedious. You can find user-contributed guides and transaction set definitions in `lib/stupidedi/contrib`, and the ones I'm able to maintain are in `lib/stupidedi/guides` and their transaction set definitions are in `versions/functional_groups/005010/transaction_set_defs`.

The first step is implementing a `TransactionSetDef`, which will let you parse, traverse, and generate an 834, but it won't do very precise error checking or searching. You can wire it in using `Config#customize`. Next, you can encode detailed specifications in a `Guide`, like which values are allowed in particular elements, which elements must or must not be present, what each occurrence of a loop means, etc. Finally you can wire the `Guide` into the configuration instead of using the `TransactionSetDef` and stupidedi will then be able to give better error messages and allow you to traverse the document more succinctly.

If you have the official X12 documentation for 834 and would like to contribute a grammar, I'll be happy to help you draft a PR. Most people instead have a "companion guide" from a particular trading partner, which has only a minor resemblance to the X12 specification. I'll still gladly help you implement that, but wouldn't encourage you to submit it as a PR -- of course user-defined grammars work the same as the ones included with the library, and you can create your own separate library of them.

Good luck and please let me know if you have questions!

**Comment by michaelachrisco** [comment]
Ya its a specific version of the 834 that is based(?) on the specs. I may need to dig up an original 834 X12 to see how well they adhere to the standard. I appreciate the help and thorough description. I am having to build out a lot of X12 docs and I would rather use a verifiable gem than a custom solution. 

Ill take a look at the guides. Thanks again!

**Comment by michaelachrisco** [comment]
Thanks for the help @kputnam! I was able to get validation working for the specific version of the 834. The only problem is the proriatary format...

If anyone has a copy of the origional 834 format, ill give a shot at adding a "standard" 834 and adding it to stupidedi.

Something like: http://www.dhcs.ca.gov/formsandpubs/laws/hipaa/Pages/2.02_834_Transaction-Benefit-Enrollment.aspx may help? Not sure...
