### ISSUE TITLE
"non-deterministic machine state" when generating 837 2310E/2010F

### ISSUE THREAD

**Issue by PetriWessman** [kputnam/stupidedi#81]
Hi, I'm trying to convert a (horrible) hand-generated EDI "generator" to use stupidedi. Slowly figuring things out, but ran into this issue (and a few others, but separate tickets for those).

When trying to generate the 837 output, I'm getting:

"non-deterministic machine state: NM1 Rendering Provider Name, NM1 Service Facility Location Name, NM1 Ambulance Pick-up Location, NM1 Ambulance Drop-off Location"

This happens if I have both 2310E (Ambulance Pickup Location) and 2310F (Ambulance Dropoff Location) defined, does not happen with only one of them. So the presence of both is confusing the parser, even though they _should_ be unambigious.

The relevant code snippet is:

```ruby
        config = Stupidedi::Config.hipaa
        b = Stupidedi::Builder::BuilderDsl.build(config)
...
              b.CLM claim.original_id,
                    claim.claim_amount,
                    nil, nil,
                    b.composite(parameters.place_of_service_code, 'B', '1'),
                    'Y', 'A', 'Y', 'Y'

              b.DTP '454', 'D8',
                  claim.claim_date

              b.HI b.composite(*(claim.procedure_code.split ':'))

# 2310E
              b.NM1 'PW', '2'
              b.N3 claim.pickup_address
              b.N4 claim.pickup_city, claim.pickup_state, claim.pickup_postcode

# 2310F, HAVING THIS SEGMENT CAUSES THE ERROR
              b.NM1 '42', '2'
              b.N3 claim.dropoff_address
              b.N4 claim.dropoff_city, claim.dropoff_state, claim.dropoff_postcode

              b.LX '1'

              b.SV1 b.composite('HC', claim.hcpcs_code),
                    claim.claim_amount,
                    'UN', '1', nil, nil, b.composite('1')

              b.DTP '472', 'D8',
                    claim.claim_date
...

```

Any ideas on how I could get around this? Everything else is now working fine, but the client wants to have both the pickup and the dropoff addresses included per claim.

**Comment by PetriWessman** [comment]
Added: looks like it's specifically the 2010F segment (dropoff location) which is causing the problem. Even if I only have that defined, I get the same error. With only 2010E (pickup) defined, no problem.

**Comment by kputnam** [comment]
I can take a closer look this weekend, but I suspect the qualifier code `42` is not listed in the grammar for any of the loops, or maybe it's listed for more than one of the 2010 loops? You can check this in the source in `https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/guides/005010/`. Which version of 837 are you using specifically (or what do your GS and ST segments look like)?

You can also set the strict argument to `false` in `BuilderDsl`, which should allow you to generate ambiguous inputs without throwing an exception. 
See https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/builder/builder_dsl.rb#L23

Just for debugging, you could try this and generate the document all the way to the suspect `NM1`, but not further, and then try pretty-printing the builder or `b.machine` etc. This should show you the two (or more) different parse trees it constructed. Be aware if you generate more segments past the NM1, the ambiguity might resolve itself using the additional input, and you won't be able to tell what the problem was.

**Comment by kputnam** [comment]
Oh, I missed it the first time but you said, `non-deterministic machine state: NM1 Rendering Provider Name, NM1 Service Facility Location Name, NM1 Ambulance Pick-up Location, NM1 Ambulance Drop-off Location`. You mentioned 2010, but I think you must have meant 2310?

This means the parser doesn't know which one of those loops to generate from your input, `b.NM1 '42', '2'`. First, make sure the loop you meant to generate is one of those (looks like it), and then check the grammar:
* (2310E NM1)[https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/guides/005010/X222A1-HC837P.rb#L751]
* (2310F NM1)[https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/guides/005010/X222A1-HC837P.rb#L781]
* (2310B NM1)[https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/guides/005010/X222A1-HC837P.rb#L650]
* (2310C NM1)[https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/guides/005010/X222A1-HC837P.rb#L681]

Looking at the allowed values in those NM1*01 elements shows `42` isn't allowed by any of them. So I think it's unable to narrow down which of those `NM1`s that could occur.

I would expected the parser to tell you something like "42 is not an allowed value", so I think that could be improved (it might not check allowed values until it knows which segment definition to use). If you can send me a reproducible and minimal example that gets up to this `NM1` segment, I should be able to fix the error checking so it will tell you `42` is not valid, rather than this confusing message. You can email me privately, and fake test data is fine.

**Comment by kputnam** [comment]
One other point: why didn't it complain about the other `NM1`s in other 2310 loops like A, D, etc? Because your second element, `2` excludes those as possible matches. Those `NM1` segments only allow `1` as the second element. The remaining four `NM1`s -- B, C, E, F -- all allow `2` in the second element. Hopefully this sheds a little light on how the parser works.

**Comment by PetriWessman** [comment]
Ah! Damn, now I feel *really* stupid. It was just a matter of typo... that '42' should be '45', and I even thought I checked if (from those grammar files files you linked to). And yes, 2310, not 2010, that was a typo too.

Guess I was just tired, after juggling this for all too many hours. I expect things to work when I change that '42' into the '45' it should be, first thing on Monday...

A **huge** thanks for your exhaustive explanation, that does clarify how the parser works, so maybe I can figure the next one out by myself. :)

I'll close this issue as soon as I verify that if was just due to that wrong number (Monday). Thanks again.

**Comment by PetriWessman** [comment]
I'll look into writing a minimal example of this, as requested, if you want to improve the error message in cases like this.

**Comment by kputnam** [comment]
No reason to feel stupid, I feel the blame on this one! If the error message was more helpful, you probably would have been able to fix it immediately, at least that's how I think it ought to be. Thanks for the report and I'll look forward to your example.

**Comment by PetriWessman** [comment]
Confirmed, works fine with '42' -> '45. Excellent. I'll close this ticket and send you a standalone test file later today.

**Comment by PetriWessman** [comment]
Just to confirm: I sent you email May 10th to an address which I *think* is yours (gmail) with a test code sample for this case (and one other issue having to do with ST..SE counts. Did you ever receive it or did it end up in a spam filter somewhere? :)

**Comment by PetriWessman** [comment]
In case you didn't receive it, here's the test file via Gist. I'll reopen this ticket so that you notice this, please close afterwards :). Thanks.

https://gist.github.com/PetriWessman/d2e574ec2760bd779f2e68fe22e964d1

**Comment by kputnam** [comment]
Sorry I hadn't replied to your email but I did get it. I've just been behind on email!

Thanks again for providing an example, it might be a while before I can act on it, but having an example will hopefully make quick work of fixing the error message.
