### ISSUE TITLE
required segment SE is missing from table Table 3 - Summary

### ISSUE THREAD

**Issue by tamagokun** [kputnam/stupidedi#90]
I'm working on generating a 40010 850 document, but running into an issue near the end of the document.

It seems if I add a `CTT` segment, I get this error about `SE`, but if I leave `CTT` out, everything works fine. So, i'm assuming there is something wrong either in the segment definition or the transaction set definition.

Here's the error:

```
Stupidedi::Exceptions::ParseError: required segment SE is missing from table Table 3 - Summary
```

And here is a basic sample of the end:

```ruby
b.CTT order.line_items.size
b.SE count, transaction_number
b.GE '1', '1'
b.IEA '1', interchange_number
```

**Comment by tamagokun** [comment]
Not sure why, but moving `SE` to its own table def seemed to fix it.

```ruby
d::TableDef.header("Table 4 - Trailer",
  s:: SE.use( 30, r::Mandatory, d::RepeatCount.bounded(1)))
```

**Comment by kputnam** [comment]
Hey Mike, I'm not familiar with the 850 grammar, but I've noticed a similar thing with some of the HIPAA grammars. The documentation makes it look like `SE` goes at the end of a `TableDef.detail`, but that would mean it could be repeated (since detail tables can repeat).

I think it's almost always the case that `SE` should be in a `TableDef.summary` (you might want to change yours from `.header`). This way you can't end up with more than one `SE` per `ST`.

**Comment by tamagokun** [comment]
Ah, thanks for that. I'm still wrapping my head around EDI documents.

Changing `header` to `summary` here worked like a champ (https://github.com/kputnam/stupidedi/blob/master/lib/stupidedi/contrib/004010/transaction_set_defs/PO850.rb#L42)

**Comment by kputnam** [comment]
@irobayna I noticed in that file (PO850 for 4010) that Table 2 is also `header` but should probably be `detail`. Not sure if it matters, but thought you might want to take a look.
